version: 0.2

phases:
  install:
    commands:
      - echo installing node 12
      - apt-get install curl
      - curl -sL https://deb.nodesource.com/setup_13.x | bash -
      - apt-get install nodejs
      - node -v
      - echo installing yarn
      - npm install --global yarn
  pre_build:
    commands:
      - echo installing 
      - cd ./client
      - yarn
  build:
    commands:
      - echo building...
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: client/build

  env:
    variables:
      REACT_APP_STRIPE: $REACT_APP_STRIPE
      REACT_APP_BASE_URL: $REACT_APP_BASE_URL
