version: 0.2

phases:
  install:
    commands:
      - echo installing node 12
      - sudo apt-get install curl
      - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
      - sudo apt-get install nodejs
      - node -v
      - echo installing yarn
      - npm install --global yarn
  pre_build:
    commands:
      - echo installing dependencies
      - yarn 
  build:
    commands:
      - echo building...
      - yarn build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build